# Generated by Django 5.0 on 2023-12-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_time',
            field=models.TimeField(null=True),
        ),
    ]
