# Generated by Django 5.0 on 2023-12-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0002_alter_eventmodel_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
