# Generated by Django 5.0 on 2024-01-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0004_eventmodel_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='slots',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
